language: python

python:
  - "2.7"

before_install:
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install gfortran g77
 - travis_retry sudo apt-get install libblas-dev liblapack-dev

install:
  - "pip install ."
  - "pip install -q -r requirements.txt"

script: python tests.py && ./run_all_notebooks.sh

